# SystemProgrammingLab
# Week12 - Multiplexing
# ChoiJinWoo
# 2020315798

all : client server
CC=gcc

client: client.c
	$(CC) -o $@ $^
server: server.c
	$(CC) -o $@ $^
clean:
	rm client server client.o server.o
